version: 2.1

jobs:
  python-job:
    docker:
      - image: circleci/python:3.10.1-node-browsers
    steps:
      - checkout
      - run:
          name: set up venv
          command: |
            python -m venv venv
            . venv/bin/activate
      - run:
          name: install dependencies
          command: |
            . venv/bin/activate
            pip install -r requirements.txt
            pip install allure-pytest

      - run:
          name: Install Allure CLI
          command: |
            sudo apt-get update && sudo apt-get install -y default-jre wget unzip
            wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.zip
            unzip -o allure-2.27.0.zip
            sudo mv allure-2.27.0 /opt/allure
            sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir -p allure-results
            pytest --alluredir=allure-results
            allure generate allure-results -o allure-report --clean
#            allure generate allure-results -o allure-report --clean
#            pytest --template=html1/index.html --report=report.html
#      - store_artifacts:
#          path: report.html
#          destination: python-report

      - store_artifacts:
                path: allure-report
                destination: allure-report

      - persist_to_workspace:
                root: .
                paths:
                  - allure-report

workflows:
  build-and-test:
    jobs:
      - python-job