version: 2.1

jobs:
  python-job:
    docker:
      - image: circleci/python:3.10.1-node-browsers
    steps:
      - checkout
      - run:
          name: set up venv
          command: |
            python -m venv venv
            . venv/bin/activate
      - run:
          name: install dependencies
          command: |
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Allure
          command:
            sudo npm install -g allure-commandline
      - run:
          name: Inject environment variables securely
          command: |
             echo "QA_TOKEN=QA_TOKEN" >> .env
             echo "QA_API_URL=QA_API_URL" >> .env

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --template=html1/index.html --report=report.html
      - store_artifacts:
          path: report.html
          destination: python-report

workflows:
  build-and-test:
    jobs:
      - python-job