version: 2.1

jobs:
  python-job:
    docker:
      - image: circleci/python:3.10.1-node-browsers
    steps:
      - checkout
      - run:
          name: set up venv
          command: |
            python -m venv venv
            . venv/bin/activate
      - run:
          name: install dependencies
          command: |
            pip install -r requirements.txt
            pip install allure-pytest
            . venv/bin/activate
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir -p allure-results
            pytest
            allure generate allure-results -o allure-report --clean
#            pytest --template=html1/index.html --report=report.html
#      - store_artifacts:
#          path: report.html
#          destination: python-report
      - store_artifacts:
          path: allure-report
          destination: allure-report

      - persist_to_workspace:
          root: .
          paths:
            - allure-report

#workflows:
#  build-and-test:
#    jobs:
#      - python-job